// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeY5kxJgEaXAuyJBh3GdynNlkfjlilTBs',
    appId: '1:393430103903:web:b8acc45d047030623668ea',
    messagingSenderId: '393430103903',
    projectId: 'ai-tutor-27e63',
    authDomain: 'ai-tutor-27e63.firebaseapp.com',
    databaseURL: 'https://ai-tutor-27e63-default-rtdb.firebaseio.com',
    storageBucket: 'ai-tutor-27e63.appspot.com',
    measurementId: 'G-BJK89XG22H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcr_HrshU6jBv7FtHy0qet26jIm2R3ldA',
    appId: '1:393430103903:android:7490d8ea9125dcbe3668ea',
    messagingSenderId: '393430103903',
    projectId: 'ai-tutor-27e63',
    databaseURL: 'https://ai-tutor-27e63-default-rtdb.firebaseio.com',
    storageBucket: 'ai-tutor-27e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZvrEsY1KwsPJdl6U8VUCj5YS4QVX-tlU',
    appId: '1:393430103903:ios:104e05fe9e9987da3668ea',
    messagingSenderId: '393430103903',
    projectId: 'ai-tutor-27e63',
    databaseURL: 'https://ai-tutor-27e63-default-rtdb.firebaseio.com',
    storageBucket: 'ai-tutor-27e63.appspot.com',
    iosBundleId: 'com.aitutor.aitutor',
  );

}